const sqlite3 = require('sqlite3').verbose()
const db = new sqlite3.Database('./data.db',sqlite3.OPEN_READWRITE)

db.run("CREATE TABLE EVENT (ID INT PRIMARY KEY NOT NULL, USER_ID INT, START INT, END INT, NAME TEXT, LOCATION INT, CONTENT TEXT, CATEGORY INT)");

db.run("CREATE TABLE USER (ID INT PRIMARY KEY NOT NULL, GROUP_ID INT, NAME TEXT)");

db.run("CREATE TABLE COMMUNITY (ID INT PRIMARY KEY NOT NULL, OWNER_ID INT, NAME TEXT, CONTENT TEXT)");

db.close()
